# Generated by Django 2.1.5 on 2019-01-21 22:37

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('execution', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', multiselectfield.db.fields.MultiSelectField(choices=[('CARDIO', 'CARDIO'), ('PLYO', 'PLYO'), ('WEIGHT', 'WEIGHT'), ('LAPS', 'LAPS'), ('MACHINE', 'MACHINE')], default='WEIGHT', max_length=20)),
                ('major_muscule', multiselectfield.db.fields.MultiSelectField(choices=[('FULL_BODY', 'FULL BODY'), ('BACK', 'BACK'), ('CORE', 'CORE'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS')], default='FULL_BODY', max_length=19)),
                ('minior_muscule', multiselectfield.db.fields.MultiSelectField(choices=[('BICEP', 'BICEP'), ('CALVES', 'CALVES'), ('CHEST', 'CHEST'), ('GLUTES', 'GLUTES'), ('HAMSTRINGS', 'HAMSTRINGS'), ('INNER_THIGH', 'INNER THIGH'), ('LATS', 'LATS'), ('OBLIQUE', 'OBLIQUE'), ('OUTER_THIGH', 'OUTER THIGH'), ('QUADS', 'QUADS'), ('SHOULDERS', 'SHOULDERS'), ('TRICEP', 'TRICEP')], default='BICEP', max_length=50)),
                ('name', models.CharField(max_length=100)),
                ('execution', models.CharField(blank=True, max_length=1000, null=True)),
                ('comments', models.CharField(blank=True, max_length=1000, null=True)),
                ('example', models.ImageField(blank=True, null=True, upload_to='exercise_video/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(to='weight_buddy.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('minior_muscule_used', models.CharField(blank=True, max_length=200, null=True)),
                ('comments', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='UserDetailsExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.CharField(blank=True, max_length=200, null=True)),
                ('repets', models.CharField(blank=True, max_length=200, null=True)),
                ('rest', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercises_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.ExercisesDetail')),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('training', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.Training')),
            ],
        ),
        migrations.AddField(
            model_name='training',
            name='user_details_exercises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.UserDetailsExercises'),
        ),
    ]
