# Generated by Django 2.1.3 on 2019-01-16 20:56

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Equipment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('image', models.ImageField(blank=True, null=True, upload_to='equipment_images/')),
            ],
        ),
        migrations.CreateModel(
            name='ExercisesDetail',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('CARDIO', 'CARDIO'), ('PLYO', 'PLYO'), ('WEIGHT', 'WEIGHT'), ('LAPS', 'LAPS')], default='WEIGHT', max_length=10)),
                ('major_muscule', models.CharField(choices=[('FULL_BODY', 'FULL BODY'), ('BACK', 'BACK'), ('CORE', 'CORE'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS')], default='FULL BODY', max_length=10)),
                ('minior_muscule', models.CharField(choices=[('BICEP', 'BICEP'), ('CALVES', 'CALVES'), ('CHEST', 'CHEST'), ('GLUTES', 'GLUTES'), ('HAMSTRINGS', 'HAMSTRINGS'), ('INNER_THIGH', 'INNER THIGH'), ('LATS', 'LATS'), ('OBLIQUE', 'OBLIQUE'), ('OUTER_THIGH', 'OUTER THIGH'), ('QUADS', 'QUADS'), ('SHOULDERS', 'SHOULDERS'), ('TRICEP', 'TRICEP')], default='BICEP', max_length=10)),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(blank=True, max_length=1000, null=True)),
                ('modification', models.CharField(blank=True, max_length=1000, null=True)),
                ('example', models.ImageField(blank=True, null=True, upload_to='exercise_video/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('equipment', models.ManyToManyField(to='weight_buddy.Equipment')),
            ],
        ),
        migrations.CreateModel(
            name='Training',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('PH', 'Push'), ('PL', 'Pull'), ('LG', 'Leg')], default='PH', max_length=2)),
                ('workout_name', models.CharField(max_length=200)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
