# Generated by Django 2.1.3 on 2019-01-16 21:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesdetail',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
