# Generated by Django 2.1.5 on 2019-01-22 19:11

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsexercises',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
