# Generated by Django 2.1.3 on 2018-11-30 20:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('excercise_name', models.CharField(max_length=100)),
                ('excercise_description', models.CharField(max_length=1000)),
            ],
        ),
    ]
