# Generated by Django 2.1.5 on 2019-01-22 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0002_userdetailsexercises_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='userdetailsexercises',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
