# Generated by Django 2.1.3 on 2018-11-30 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0002_exercise'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='Test',
            field=models.ManyToManyField(to='weight_buddy.Exercise'),
        ),
    ]
