# Generated by Django 2.1.3 on 2019-01-17 20:34

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0003_auto_20190117_2126'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesdetail',
            name='major_muscule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FULL_BODY', 'FULL BODY'), ('BACK', 'BACK'), ('CORE', 'CORE'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS')], default='FULL_BODY', max_length=10),
        ),
    ]
