# Generated by Django 2.1.5 on 2019-01-22 19:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0003_userdetailsexercises_name'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userdetailsexercises',
            name='exercises_detail',
        ),
    ]
