# Generated by Django 2.1.3 on 2019-01-17 20:38

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0004_auto_20190117_2134'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesdetail',
            name='major_muscule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('FULL_BODY', 'FULL BODY'), ('BACK', 'BACK'), ('CORE', 'CORE'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS')], default='FULL_BODY', max_length=19),
        ),
        migrations.AlterField(
            model_name='exercisesdetail',
            name='minior_muscule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BICEP', 'BICEP'), ('CALVES', 'CALVES'), ('CHEST', 'CHEST'), ('GLUTES', 'GLUTES'), ('HAMSTRINGS', 'HAMSTRINGS'), ('INNER_THIGH', 'INNER THIGH'), ('LATS', 'LATS'), ('OBLIQUE', 'OBLIQUE'), ('OUTER_THIGH', 'OUTER THIGH'), ('QUADS', 'QUADS'), ('SHOULDERS', 'SHOULDERS'), ('TRICEP', 'TRICEP')], default='BICEP', max_length=30),
        ),
        migrations.AlterField(
            model_name='exercisesdetail',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CARDIO', 'CARDIO'), ('PLYO', 'PLYO'), ('WEIGHT', 'WEIGHT'), ('LAPS', 'LAPS')], default='WEIGHT', max_length=20),
        ),
    ]
