# Generated by Django 2.1.5 on 2019-01-22 19:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('weight_buddy', '0004_remove_userdetailsexercises_exercises_detail'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsExercise',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sets', models.CharField(blank=True, max_length=200, null=True)),
                ('repets', models.CharField(blank=True, max_length=200, null=True)),
                ('rest', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('exercises_detail', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.ExercisesDetail')),
            ],
        ),
        migrations.RemoveField(
            model_name='userdetailsexercises',
            name='author',
        ),
        migrations.AlterField(
            model_name='training',
            name='user_details_exercises',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.UserDetailsExercise'),
        ),
        migrations.DeleteModel(
            name='UserDetailsExercises',
        ),
    ]
