# Generated by Django 2.1.3 on 2018-11-30 21:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0004_remove_training_test'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='excercises',
            field=models.ForeignKey(default=None, on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.Exercise'),
            preserve_default=False,
        ),
    ]
