# Generated by Django 2.1.5 on 2019-01-22 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0005_auto_20190122_2028'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='user_details_exercises',
        ),
        migrations.AddField(
            model_name='training',
            name='user_details_exercises',
            field=models.ManyToManyField(to='weight_buddy.UserDetailsExercise'),
        ),
        migrations.RemoveField(
            model_name='workout',
            name='training',
        ),
        migrations.AddField(
            model_name='workout',
            name='training',
            field=models.ManyToManyField(to='weight_buddy.Training'),
        ),
    ]
