# Generated by Django 2.1.3 on 2019-01-17 20:54

from django.db import migrations
import multiselectfield.db.fields
import weight_buddy.models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0005_auto_20190117_2138'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesdetail',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercisesdetail',
            name='equipment',
            field=multiselectfield.db.fields.MultiSelectField(default=1, max_length=200, verbose_name=weight_buddy.models.Equipment),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='exercisesdetail',
            name='minior_muscule',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BICEP', 'BICEP'), ('CALVES', 'CALVES'), ('CHEST', 'CHEST'), ('GLUTES', 'GLUTES'), ('HAMSTRINGS', 'HAMSTRINGS'), ('INNER_THIGH', 'INNER THIGH'), ('LATS', 'LATS'), ('OBLIQUE', 'OBLIQUE'), ('OUTER_THIGH', 'OUTER THIGH'), ('QUADS', 'QUADS'), ('SHOULDERS', 'SHOULDERS'), ('TRICEP', 'TRICEP')], default='BICEP', max_length=50),
        ),
    ]
