# Generated by Django 2.1.3 on 2018-11-30 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0005_training_excercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='excercises',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.Exercise'),
        ),
    ]
