# Generated by Django 2.1.3 on 2019-01-17 20:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0006_auto_20190117_2154'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesdetail',
            name='equipment',
        ),
        migrations.AddField(
            model_name='exercisesdetail',
            name='equipment',
            field=models.ManyToManyField(to='weight_buddy.Equipment'),
        ),
    ]
