# Generated by Django 2.1.5 on 2019-03-08 19:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0006_auto_20190122_2319'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesdetail',
            name='example_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='', verbose_name='exercise_video/thumbnail/'),
        ),
    ]
