# Generated by Django 2.1.3 on 2018-11-30 21:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0007_auto_20181130_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='excercise_description',
            field=models.CharField(max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='excercise_name',
            field=models.CharField(max_length=100, null=True),
        ),
    ]
