# Generated by Django 2.1.3 on 2019-01-19 22:02

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0007_auto_20190117_2158'),
    ]

    operations = [
        migrations.CreateModel(
            name='UserDetailsExercises',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=200)),
                ('sets', models.CharField(blank=True, max_length=200, null=True)),
                ('repets', models.CharField(blank=True, max_length=200, null=True)),
                ('rest', models.CharField(blank=True, max_length=200, null=True)),
                ('notes', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.CreateModel(
            name='WorkOut',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=200, null=True)),
            ],
        ),
        migrations.RemoveField(
            model_name='training',
            name='published_date',
        ),
        migrations.RemoveField(
            model_name='training',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='training',
            name='comments',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='minior_muscule_used',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='exercisesdetail',
            name='type',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('CARDIO', 'CARDIO'), ('PLYO', 'PLYO'), ('WEIGHT', 'WEIGHT'), ('LAPS', 'LAPS'), ('MACHINE', 'MACHINE')], default='WEIGHT', max_length=20),
        ),
    ]
