# Generated by Django 2.1.5 on 2019-03-08 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0007_exercisesdetail_example_thumbnail'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesdetail',
            name='example_thumbnail',
        ),
    ]
