# Generated by Django 2.1.3 on 2019-01-20 18:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0008_auto_20190119_2302'),
    ]

    operations = [
        migrations.AlterField(
            model_name='userdetailsexercises',
            name='name',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
