# Generated by Django 2.1.5 on 2019-03-12 21:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0008_remove_exercisesdetail_example_thumbnail'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesdetail',
            name='example_thumbnail',
            field=models.ImageField(blank=True, null=True, upload_to='exercise_video/thumbnail/'),
        ),
    ]
