# Generated by Django 2.1.3 on 2018-11-30 21:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0008_auto_20181130_2223'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='excercises',
        ),
    ]
