# Generated by Django 2.1.3 on 2018-11-30 21:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0009_remove_training_excercises'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercise',
            name='excercise_description',
            field=models.CharField(max_length=1000),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='excercise_name',
            field=models.CharField(max_length=100),
        ),
    ]
