# Generated by Django 2.1.3 on 2018-11-30 21:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0010_auto_20181130_2228'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='exercise',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='weight_buddy.Exercise'),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='excercise_description',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
        migrations.AlterField(
            model_name='exercise',
            name='excercise_name',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
