# Generated by Django 2.1.3 on 2018-11-30 22:08

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0014_auto_20181130_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercise',
            field=models.ForeignKey(blank=True, default=1, null=True, on_delete=django.db.models.deletion.SET_NULL, to='weight_buddy.Exercises'),
        ),
    ]
