# Generated by Django 2.1.3 on 2018-12-01 09:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0016_auto_20181130_2313'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercise_name',
        ),
    ]
