# Generated by Django 2.1.3 on 2018-12-01 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0018_auto_20181201_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='workout_name',
            field=models.CharField(default='Hello', max_length=200),
            preserve_default=False,
        ),
    ]
