# Generated by Django 2.1.3 on 2018-12-01 16:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0020_auto_20181201_1751'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercises',
            name='repetitions_number',
        ),
        migrations.RemoveField(
            model_name='exercises',
            name='set_number',
        ),
        migrations.AddField(
            model_name='exercises',
            name='set_repetitions_number',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
