# Generated by Django 2.1.3 on 2018-12-01 17:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0022_auto_20181201_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='training',
            name='exercise_five',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_five', to='weight_buddy.Exercises'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_four',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_four', to='weight_buddy.Exercises'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_tree',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_tree', to='weight_buddy.Exercises'),
        ),
        migrations.AddField(
            model_name='training',
            name='exercise_two',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_two', to='weight_buddy.Exercises'),
        ),
        migrations.AddField(
            model_name='training',
            name='weight_five',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='weight_four',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='weight_tree',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='training',
            name='weight_two',
            field=models.SmallIntegerField(blank=True, null=True),
        ),
    ]
