# Generated by Django 2.1.3 on 2018-12-01 20:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0024_auto_20181201_1845'),
    ]

    operations = [
        migrations.AlterField(
            model_name='training',
            name='exercise_five',
            field=models.ForeignKey(default=6, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_five', to='weight_buddy.Exercises'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise_four',
            field=models.ForeignKey(default=5, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_four', to='weight_buddy.Exercises'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise_one',
            field=models.ForeignKey(default=2, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_one', to='weight_buddy.Exercises'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise_tree',
            field=models.ForeignKey(default=4, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_tree', to='weight_buddy.Exercises'),
        ),
        migrations.AlterField(
            model_name='training',
            name='exercise_two',
            field=models.ForeignKey(default=3, on_delete=django.db.models.deletion.SET_DEFAULT, related_name='exercise_two', to='weight_buddy.Exercises'),
        ),
    ]
