# Generated by Django 2.1.3 on 2019-01-03 19:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0025_auto_20181201_2123'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisesSet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
    ]
