# Generated by Django 2.1.3 on 2019-01-03 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0026_exercisesset'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExercisesDetails',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('workout_type', models.CharField(choices=[('CHEST', 'CHEST'), ('DELTS', 'DELTS'), ('TRICEPS', 'TRICEPS'), ('BACK', 'BACK'), ('BICEPS', 'BICEPS'), ('FOREARMS', 'FOREARMS'), ('LEGS', 'LEGS'), ('ABS', 'ABS')], default='CHEST', max_length=10)),
                ('excercise_name', models.CharField(max_length=100)),
                ('excercise_description', models.CharField(blank=True, max_length=1000, null=True)),
            ],
        ),
        migrations.DeleteModel(
            name='ExercisesSet',
        ),
    ]
