# Generated by Django 2.1.3 on 2019-01-06 20:19

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0027_auto_20190103_2208'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exercisesdetails',
            name='workout_type',
        ),
        migrations.AddField(
            model_name='exercisesdetails',
            name='created_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='exercisesdetails',
            name='excercise_type',
            field=models.CharField(choices=[('CARDIO', 'CARDIO'), ('PLYO', 'PLYO'), ('WEIGHT', 'WEIGHT'), ('LAPS', 'LAPS')], default='WEIGHT', max_length=10),
        ),
        migrations.AddField(
            model_name='exercisesdetails',
            name='published_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
