# Generated by Django 2.1.3 on 2019-01-06 20:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0028_auto_20190106_2119'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='training',
            name='exercise',
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercise_five',
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercise_four',
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercise_one',
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercise_tree',
        ),
        migrations.RemoveField(
            model_name='training',
            name='exercise_two',
        ),
        migrations.RemoveField(
            model_name='training',
            name='weight',
        ),
        migrations.RemoveField(
            model_name='training',
            name='weight_five',
        ),
        migrations.RemoveField(
            model_name='training',
            name='weight_four',
        ),
        migrations.RemoveField(
            model_name='training',
            name='weight_one',
        ),
        migrations.RemoveField(
            model_name='training',
            name='weight_tree',
        ),
        migrations.RemoveField(
            model_name='training',
            name='weight_two',
        ),
        migrations.DeleteModel(
            name='Exercises',
        ),
    ]
