# Generated by Django 2.1.3 on 2019-01-06 20:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0029_auto_20190106_2152'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ExercisesDetails',
            new_name='ExercisesDetail',
        ),
    ]
