# Generated by Django 2.1.3 on 2019-01-07 22:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0031_auto_20190107_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exercisesdetail',
            name='excercise_major_muscule',
            field=models.CharField(choices=[('FULL_BODY', 'FULL BODY'), ('BACK', 'BACK'), ('CORE', 'CORE'), ('ARMS', 'ARMS'), ('LEGS', 'LEGS')], default='FULL BODY', max_length=10),
        ),
        migrations.AlterField(
            model_name='exercisesdetail',
            name='excercise_minior_muscule',
            field=models.CharField(choices=[('BICEP', 'BICEP'), ('CALVES', 'CALVES'), ('CHEST', 'CHEST'), ('GLUTES', 'GLUTES'), ('HAMSTRINGS', 'HAMSTRINGS'), ('INNER_THIGH', 'INNER THIGH'), ('LATS', 'LATS'), ('OBLIQUE', 'OBLIQUE'), ('OUTER_THIGH', 'OUTER THIGH'), ('QUADS', 'QUADS'), ('SHOULDERS', 'SHOULDERS'), ('TRICEP', 'TRICEP')], default='FULL_BODY', max_length=10),
        ),
    ]
