# Generated by Django 2.1.3 on 2019-01-08 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0032_auto_20190107_2353'),
    ]

    operations = [
        migrations.AddField(
            model_name='exercisesdetail',
            name='excercise_example',
            field=models.ImageField(blank=True, upload_to='exercise_video'),
        ),
        migrations.AddField(
            model_name='exercisesdetail',
            name='excercise_modification',
            field=models.CharField(blank=True, max_length=1000, null=True),
        ),
    ]
