# Generated by Django 2.1.3 on 2019-01-08 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('weight_buddy', '0033_auto_20190108_2212'),
    ]

    operations = [
        migrations.RenameField(
            model_name='exercisesdetail',
            old_name='excercise_description',
            new_name='description',
        ),
        migrations.RenameField(
            model_name='exercisesdetail',
            old_name='excercise_example',
            new_name='example',
        ),
        migrations.RenameField(
            model_name='exercisesdetail',
            old_name='excercise_major_muscule',
            new_name='major_muscule',
        ),
        migrations.RenameField(
            model_name='exercisesdetail',
            old_name='excercise_minior_muscule',
            new_name='minior_muscule',
        ),
        migrations.RenameField(
            model_name='exercisesdetail',
            old_name='excercise_modification',
            new_name='modification',
        ),
        migrations.RenameField(
            model_name='exercisesdetail',
            old_name='excercise_name',
            new_name='name',
        ),
        migrations.RenameField(
            model_name='exercisesdetail',
            old_name='excercise_type',
            new_name='type',
        ),
    ]
